package pcpricesimulator;


import javax.swing.ImageIcon;
import java.util.HashMap;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gazel
 */
public class LoginForm extends javax.swing.JFrame {
    // ALL THIS CODE MADE BY GAZEL AVERROUS
    public static LoginForm loginForm;
    public static RegisterForm registerForm;
    public static MainForm mainForm;
    public static User currentUser;
    public UserWishlistForm userWishlistForm;

    //new User("jegal", "224466");
    /**
     * Creates new form PcPriceSimulatorForm
     */
    public LoginForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 70, -1));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PC PRICE SIMULATOR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 350, 70));
        jPanel1.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 71, -1));

        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 90, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Doesn't have account?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcBackground.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, -490, 800, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        registerForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = tfUsername.getText();
        String password = String.valueOf(tfPassword.getPassword());

        boolean doesExist = false;
        for(User c: User.getUserList()){
            
            if(c.getName().equalsIgnoreCase(username)){
                doesExist = true;
                if(c.getPassword().equalsIgnoreCase(password)){
                    LoginForm.loginForm.setVisible(false);
                    currentUser = c;
                    mainForm = new MainForm(currentUser.getName());
                   
                    
                    if (currentUser.getUserWishlistForm() == null){
                        currentUser.setUserWishlistForm(new UserWishlistForm(currentUser.getName()));
                    } else {
                        currentUser.setUserWishlistForm(currentUser.getUserWishlistForm());
                    }
                    mainForm.setVisible(true);
                    tfPassword.setText("");
                    tfUsername.setText("");
                    showMessageDialog(null, "Welcome to Pc Price Simulator!");
                } else {
                    showMessageDialog(null, "wrong password");
                    tfPassword.setText("");
                }
            }
        }
        if(!doesExist){
            showMessageDialog(null, "username not founded");
            tfPassword.setText("");
            tfUsername.setText("");
        }     
        
        
        
        
        
        
        // System.out.print(username + " " + password);
        // new User(username, password);
        // System.out.println(User.getUserList());  
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        //      ALL THIS CODE MADE BY GAZEL AVERROUS
        
        // ADDING ALL ITEM TO THE LIST
        Components.cpuList.put("<Default>", 0d);
        Components.cpuList.put("AMD Ryzen 9", 1_600_000d);
        Components.cpuList.put("Intel core i9", 1_500_000d);
        Components.cpuList.put("AMD Ryzen 8", 1_100_000d);
        Components.cpuList.put("Intel core i7", 1_900_000d);
        
        Components.cpuCoolerList.put("<Default>", 0d);
        Components.cpuCoolerList.put("Cooler Master Hyper 212 EVO", 750_000d);
        Components.cpuCoolerList.put("Cooler Master Hyper H412R CPU", 400_000d);
        Components.cpuCoolerList.put("Cooler Master Hyper T20", 850_000d);
        Components.cpuCoolerList.put("Cooler Master Hyper 212 Halo White", 900_000d);
        
        Components.motherboardList.put("<Default>", 0d);
        Components.motherboardList.put("ASRock MB TRX40 Creator AMD Ryzen", 22_900_000d);
        Components.motherboardList.put("ASUS ROG Zenith II Extreme Alpha TRX40", 8_050_000d);
        Components.motherboardList.put("Asus ROG Strix TRX40-E Gaming AMD", 3_400_000d);
        Components.motherboardList.put("GIGABYTE TRX40 AORUS Master", 12_900_000d);
        
        Components.memoryList.put("<Default>", 0d);
        Components.memoryList.put("Corsair Vengeance LPX 16 GB", 700_000d);
        Components.memoryList.put("G.Skill Ripjaws V 32 GB", 900_000d);
        Components.memoryList.put("TEAMGROUP T-Force Vulcan Z 32 GB", 800_000d);
        Components.memoryList.put("Corsair Vengeance RGB Pro 32 GB", 1_900_000d);
        
        Components.storageList.put("<Default>", 0d);
        Components.storageList.put("Samsung 970 Evo Plus", 899_000d);
        Components.storageList.put("Western Digital Black SN770", 700_000d);
        Components.storageList.put("Samsung 870 Evo", 750_000d);
        Components.storageList.put("Crucial P3 Plus", 1_300_000d);
        
        Components.graphicsCardList.put("<Default>", 0d);
        Components.graphicsCardList.put("MSI GeForce RTX 3060 Ventus 2X 12G", 4_200_000d);
        Components.graphicsCardList.put("Asus TUF GAMING", 12_100_000d);
        Components.graphicsCardList.put("Asus ROG STRIX GAMING OC", 29_950_000d);
        Components.graphicsCardList.put("MSI MECH 2X OC", 9_000_000d);
        
        Components.caseList.put("<Default>", 0d);
        Components.caseList.put("Corsair 4000D Airflow", 1_500_000d);
        Components.caseList.put("NZXT H5 Flow", 1_770_000d);
        Components.caseList.put("Lian Li O11 Dynamic EVO", 2_250_000d);
        Components.caseList.put("Phanteks Eclipse G360A", 1_900_000d);
        
        Components.powerSupplyList.put("<Default>", 0d);
        Components.powerSupplyList.put("Corsair RM850x (2021)", 1_900_000d);
        Components.powerSupplyList.put("Thermaltake Toughpower GX2", 3_270_000d);
        Components.powerSupplyList.put("EVGA 700 GD", 4_350_000d);
        Components.powerSupplyList.put("Cooler Master MWE Gold 850", 2_400_000d);
        
        Components.monitorList.put("<Default>", 0d);
        Components.monitorList.put(" Asus TUF Gaming VG27AQ", 4_500_000d);
        Components.monitorList.put("Asus VG248QG", 2_920_000d);
        Components.monitorList.put("Gigabyte M27Q", 4_150_000d);
        Components.monitorList.put("Samsung Odyssey G7", 7_100_000d);
        
        
        
        // MAKING ALL FORMS
        loginForm = new LoginForm();
        registerForm = new RegisterForm();
        
        // MAKING USER TESTER
        User.clearUserList();
        new User("kaela", "224466");
        new User("gazel", "664422");
        new User("yopi", "242466");
        User.showUserList();
        
        
        

        

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                loginForm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
