package pcpricesimulator;


import java.awt.Component;
import java.awt.Image;
import static java.lang.String.format;
import javax.swing.ImageIcon;
import java.util.HashMap;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.SwingConstants;


/*
 * Click nbfs://nbhost/SystemFileSystem/Timportemplates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gazel
 */
public class MainForm extends javax.swing.JFrame {
    
    static private Double currentPrice;
    
    /**
     * Creates new form PcPriceSimulatorForm
     */
    public MainForm(String username) {
        // ALL THIS CODE MADE BY GAZEL AVERROUS

        initComponents();
        scaleimage();
        btnSetWishList.setEnabled(false);
       

        
        
        // labelUserName.setAlignmentX(Component.CENTER_ALIGNMENT);
        // labelUserName.setAlignmentY(Component.CENTER_ALIGNMENT);
        labelUserName.setText(username);
        labelUserName.setHorizontalAlignment(SwingConstants.CENTER);

        // labelPrice.setText(String.format("Rp%,.2f",(Components.cpuList.get("Intel core i7"))));
        
        // ADDING ALL COMPONENT FROM COMPONENTS LIST INTO COMBOBOX
        for(String cpu: Components.cpuList.keySet()){
            if(!cpu.equalsIgnoreCase("<Default>")){
                cbCPU.addItem(cpu);
            }
            // System.out.println(cpu);
        }
        for(String cpuCooler: Components.cpuCoolerList.keySet()){
            if(!cpuCooler.equalsIgnoreCase("<Default>")){
                cbCPUCooler.addItem(cpuCooler);
            }
            // System.out.println(cpu);
        }
        for(String motherboard: Components.motherboardList.keySet()){
            if(!motherboard.equalsIgnoreCase("<Default>")){
                cbMotherboard.addItem(motherboard);
            }
            // System.out.println(cpu);
        }
        for(String memory: Components.memoryList.keySet()){
             if(!memory.equalsIgnoreCase("<Default>")){
                cbMemory.addItem(memory);
            }
            // System.out.println(cpu);
        }
        for(String storage: Components.storageList.keySet()){
            if(!storage.equalsIgnoreCase("<Default>")){
                cbStorage.addItem(storage);
            }
            // System.out.println(cpu);
        }
        for(String graphicsCard: Components.graphicsCardList.keySet()){
            if(!graphicsCard.equalsIgnoreCase("<Default>")){
                cbGraphicsCard.addItem(graphicsCard);
            }
            // System.out.println(cpu);
        }
        for(String caseComputer: Components.caseList.keySet()){
            if(!caseComputer.equalsIgnoreCase("<Default>")){
                cbCase.addItem(caseComputer);
            }
            // System.out.println(cpu);
        }        
        for(String powerSupply: Components.powerSupplyList.keySet()){
            if(!powerSupply.equalsIgnoreCase("<Default>")){
                cbPowerSupply.addItem(powerSupply);
            }
            // System.out.println(cpu);
        }
        for(String monitor: Components.monitorList.keySet()){
            if(!monitor.equalsIgnoreCase("<Default>")){
                cbMonitor.addItem(monitor);
            }
            // System.out.println(cpu);
        }
        
        
        
    }
    
    public void scaleimage(){
        ImageIcon icon = new ImageIcon("C:\\Users\\gazel\\OneDrive\\Dokumen\\NetBeansProjects\\PcPriceSimulator\\src\\pcpricesimulator\\defaultpp.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(pplabel.getWidth(), pplabel.getHeight(), Image.SCALE_SMOOTH);  
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        pplabel.setIcon(scaledIcon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbMonitor = new javax.swing.JComboBox<>();
        cbCPU = new javax.swing.JComboBox<>();
        cbCPUCooler = new javax.swing.JComboBox<>();
        cbMotherboard = new javax.swing.JComboBox<>();
        cbMemory = new javax.swing.JComboBox<>();
        cbStorage = new javax.swing.JComboBox<>();
        cbGraphicsCard = new javax.swing.JComboBox<>();
        cbCase = new javax.swing.JComboBox<>();
        cbPowerSupply = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        labelPrice = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        pplabel = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        btnWishList = new javax.swing.JButton();
        btnSetWishList = new javax.swing.JButton();
        btnCount = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPU :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPU Cooler :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Motherboard :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Memory :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Storage :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Graphics Card :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Case :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Power Supply :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PC PRICE SIMULATOR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 350, 70));

        cbMonitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Default>" }));
        cbMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonitorActionPerformed(evt);
            }
        });
        jPanel1.add(cbMonitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 190, -1));

        cbCPU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Default>" }));
        cbCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCPUActionPerformed(evt);
            }
        });
        jPanel1.add(cbCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 190, -1));

        cbCPUCooler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Default>" }));
        cbCPUCooler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCPUCoolerActionPerformed(evt);
            }
        });
        jPanel1.add(cbCPUCooler, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 190, -1));

        cbMotherboard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Default>" }));
        cbMotherboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMotherboardActionPerformed(evt);
            }
        });
        jPanel1.add(cbMotherboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 190, -1));

        cbMemory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Default>" }));
        cbMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMemoryActionPerformed(evt);
            }
        });
        jPanel1.add(cbMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, -1));

        cbStorage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Default>" }));
        cbStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStorageActionPerformed(evt);
            }
        });
        jPanel1.add(cbStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 190, -1));

        cbGraphicsCard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Default>" }));
        cbGraphicsCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGraphicsCardActionPerformed(evt);
            }
        });
        jPanel1.add(cbGraphicsCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 190, -1));

        cbCase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Default>" }));
        cbCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCaseActionPerformed(evt);
            }
        });
        jPanel1.add(cbCase, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 190, -1));

        cbPowerSupply.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Default>" }));
        cbPowerSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPowerSupplyActionPerformed(evt);
            }
        });
        jPanel1.add(cbPowerSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 190, -1));

        jPanel2.setBackground(new java.awt.Color(205, 138, 250));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel2.setForeground(new java.awt.Color(255, 153, 153));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("TOTAL PRICE");

        labelPrice.setBackground(new java.awt.Color(51, 51, 51));
        labelPrice.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        labelPrice.setForeground(new java.awt.Color(51, 51, 51));
        labelPrice.setText("Rp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPrice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 160, 100));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Monitor :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 80, 30));
        jPanel1.add(pplabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 40, 40));

        labelUserName.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        labelUserName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(labelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 380, 70, 20));

        btnWishList.setText("My Wish List");
        btnWishList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWishListActionPerformed(evt);
            }
        });
        jPanel1.add(btnWishList, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 110, 30));

        btnSetWishList.setText("Set To My Wisht List");
        btnSetWishList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetWishListActionPerformed(evt);
            }
        });
        jPanel1.add(btnSetWishList, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 140, 30));

        btnCount.setText("Count");
        btnCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountActionPerformed(evt);
            }
        });
        jPanel1.add(btnCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 80, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcpricesimulator/pcBackgroundBlur_1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, -490, 800, 1020));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void cbMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMonitorActionPerformed

    private void cbCPUCoolerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCPUCoolerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCPUCoolerActionPerformed

    private void cbMotherboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMotherboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMotherboardActionPerformed

    private void cbMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMemoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMemoryActionPerformed

    private void cbStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStorageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStorageActionPerformed

    private void cbGraphicsCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGraphicsCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGraphicsCardActionPerformed

    private void cbCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCaseActionPerformed

    private void cbPowerSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPowerSupplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPowerSupplyActionPerformed

    private void cbCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCPUActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int x;
        x=JOptionPane.showConfirmDialog(null, "Are you Sure?", "Confirm", JOptionPane.YES_NO_OPTION);
        
        if(x==JOptionPane.YES_NO_OPTION){
            LoginForm.loginForm.setVisible(true);
            LoginForm.mainForm.setVisible(false);
            LoginForm.currentUser = null;
        } else {
            return;
        }
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnWishListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWishListActionPerformed
        // TODO add your handling code here:
        User currentUser = LoginForm.currentUser;

        
        LoginForm.mainForm.setVisible(false);
        currentUser.getUserWishlistForm().setVisible(true);
    }//GEN-LAST:event_btnWishListActionPerformed

    private void btnCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountActionPerformed
        // TODO add your handling code here:
        Double cpu = Components.cpuList.get(cbCPU.getSelectedItem());
        Double cpuCooler = Components.cpuCoolerList.get(cbCPUCooler.getSelectedItem());
        Double case1 = Components.caseList.get(cbCase.getSelectedItem());
        Double graphicsCard = Components.graphicsCardList.get(cbGraphicsCard.getSelectedItem());
        Double memory = Components.memoryList.get(cbMemory.getSelectedItem());
        Double monitor = Components.monitorList.get(cbMonitor.getSelectedItem());
        Double motherboard = Components.motherboardList.get(cbMotherboard.getSelectedItem());
        Double powerSupply = Components.powerSupplyList.get(cbPowerSupply.getSelectedItem());
        Double storage = Components.storageList.get(cbStorage.getSelectedItem());
        
        if(cpu == 0d || cpuCooler == 0d || case1 == 0d || graphicsCard == 0d || memory == 0d || monitor == 0d || motherboard == 0d || powerSupply == 0d || storage == 0d){
            showMessageDialog(null, "Please select all your components!");
        } else {
            Double total = cpu + cpuCooler + case1 + graphicsCard + memory + monitor + motherboard + powerSupply + storage;
            MainForm.currentPrice = total;
            labelPrice.setText(String.format("Rp%,.2f",(total)));
            btnSetWishList.setEnabled(true);
        }

    }//GEN-LAST:event_btnCountActionPerformed

    private void btnSetWishListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetWishListActionPerformed
        // TODO add your handling code here:
        User currentUser = LoginForm.currentUser;

        
        
        
        String cpu = (String) cbCPU.getSelectedItem();
        String cpuCooler = (String) cbCPUCooler.getSelectedItem();
        String case1 = (String) cbCase.getSelectedItem();
        String graphicsCard = (String) cbGraphicsCard.getSelectedItem();
        String memory = (String) cbMemory.getSelectedItem();
        String monitor = (String) cbMonitor.getSelectedItem();
        String motherboard = (String) cbMotherboard.getSelectedItem();
        String powerSupply = (String) cbPowerSupply.getSelectedItem();
        String storage = (String) cbStorage.getSelectedItem();
        
        
        currentUser.setUserComponents(cpu, cpuCooler, motherboard, memory, storage, graphicsCard, case1, powerSupply, monitor, MainForm.currentPrice);
                
        cbCPU.setSelectedItem("<Default>");
        cbCPUCooler.setSelectedItem("<Default>");
        cbMotherboard.setSelectedItem("<Default>");
        cbMemory.setSelectedItem("<Default>");
        cbStorage.setSelectedItem("<Default>");
        cbGraphicsCard.setSelectedItem("<Default>");
        cbCase.setSelectedItem("<Default>");
        cbPowerSupply.setSelectedItem("<Default>");
        cbMonitor.setSelectedItem("<Default>");
        labelPrice.setText("Rp0,00");
        
                
        currentUser.getUserWishlistForm().setVisible(true);
        LoginForm.mainForm.setVisible(false);
        btnSetWishList.setEnabled(false);
    }//GEN-LAST:event_btnSetWishListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCount;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSetWishList;
    private javax.swing.JButton btnWishList;
    private javax.swing.JComboBox<String> cbCPU;
    private javax.swing.JComboBox<String> cbCPUCooler;
    private javax.swing.JComboBox<String> cbCase;
    private javax.swing.JComboBox<String> cbGraphicsCard;
    private javax.swing.JComboBox<String> cbMemory;
    private javax.swing.JComboBox<String> cbMonitor;
    private javax.swing.JComboBox<String> cbMotherboard;
    private javax.swing.JComboBox<String> cbPowerSupply;
    private javax.swing.JComboBox<String> cbStorage;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JLabel pplabel;
    // End of variables declaration//GEN-END:variables
}
